class NewWindow(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self.var = tk.StringVar(self)
        self.var.set("CN")
        self.buttonComplete = tk.Button(self, text="Complete", command=BO.GetFinalArrays)
        self.frame = tk.Frame(self, width=450, height=23)
        self.entry2 = tk.Text(self.frame, width=10)
        self.entry = tk.Text(self.frame, width=30)
        self.button2 = tk.Button(self.frame, text="Done", command=BO.choose_array)
        self.button = tk.Button(self.frame, text="add arrangement", command=self.add_arrangement)
        self.w = tk.OptionMenu(self.frame, self.var, "×1", "×2", '×3', '×1~2', '×2~3', '×0~1', '×4', '×2hmz')
        self.buttonComplete.pack(side='top', fill="x")
        self.frame.pack()
        self.frame.pack_propagate(False)
        self.button2.pack(side='right')
        self.button.pack(side='right')
        self.entry2.pack(side='left')
        self.w.pack(side="right")
        self.entry.pack()

    def add_arrangement(self):
        self.var = tk.StringVar(self)
        self.var.set("CN")
        self.frame = tk.Frame(self, width=450, height=23)
        self.entry2 = tk.Text(self.frame, width=10)
        self.entry = tk.Text(self.frame, width=30)
        self.button2 = tk.Button(self.frame, text="Done", command=BO.choose_array)
        self.button = tk.Button(self.frame, text="add arrangement", command=self.add_arrangement)
        self.w = tk.OptionMenu(self.frame, self.var, "×1", "×2", '×3', '×1~2', '×2~3', '×0~1', '×4', '×2hmz')
        self.frame.pack()
        self.frame.pack_propagate(False)
        self.button2.pack(side='right')
        self.button.pack(side='right')
        self.entry2.pack(side='left')
        self.w.pack(side="right")
        self.entry.pack()
